# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn.functional as F

# %% auto 0
__all__ = ['NormalizedCrossCorrelation2d',"MeanSquaredError2d", 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d',
           'MutualInformation', 'LogGeodesicSE3', 'DoubleGeodesicSE3', 'StructuralSimilarityIndex2d']

# %% ../notebooks/api/05_metrics.ipynb 6
from einops import rearrange


def to_patches(x, patch_size):
    x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")

# %% ../notebooks/api/05_metrics.ipynb 7
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images."""

    def __init__(self, patch_size=None, eps=1e-5):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps

    def forward(self, x1, x2):
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size)
            x2 = to_patches(x2, self.patch_size)
        assert x1.shape == x2.shape, "Input images must be the same size"
        _, c, h, w = x1.shape
        x1, x2 = self.norm(x1), self.norm(x2)
        score = torch.einsum("b...,b...->b", x1, x2)
        score /= c * h * w
        return score

    def norm(self, x):
        mu = x.mean(dim=[-1, -2], keepdim=True)
        var = x.var(dim=[-1, -2], keepdim=True, correction=0) + self.eps
        std = var.sqrt()
        return (x - mu) / std


class MeanSquaredError2d(torch.nn.Module):
    """Compute Mean Squared Error (MSE) between two batches of images."""

    def __init__(self, patch_size=None, reduction='mean'):
        super().__init__()
        self.patch_size = patch_size
        assert reduction in ['mean', 'sum', 'none'], \
            "Reduction must be 'mean', 'sum', or 'none'"
        self.reduction = reduction

    def forward(self, x1, x2):
        if self.patch_size is not None:
            x1 = self.to_patches(x1, self.patch_size)
            x2 = self.to_patches(x2, self.patch_size)
        assert x1.shape == x2.shape, "Input images must be the same size"

        # 计算逐像素的平方误差
        squared_diff = (x1 - x2) ** 2

        # 按通道和空间维度求和 (B, C, H, W) -> (B,)
        if self.reduction == 'mean':
            loss = squared_diff.mean(dim=[1, 2, 3])  # 对每个样本取平均
        elif self.reduction == 'sum':
            loss = squared_diff.sum(dim=[1, 2, 3])  # 对每个样本求和
        else:  # 'none'
            loss = squared_diff  # 保持 (B, C, H, W)

        return loss*0.01

    @staticmethod
    def to_patches(x, patch_size):
        """将图像分割为局部块 (类似 NCC 的实现)"""
        b, c, h, w = x.shape
        ph, pw = patch_size
        x = x.unfold(2, ph, ph).unfold(3, pw, pw)  # (B, C, H/ph, W/pw, ph, pw)
        x = x.contiguous().view(b, c, -1, ph, pw)  # (B, C, num_patches, ph, pw)
        return x

class StructuralSimilarityIndex2d(torch.nn.Module):
    """Compute Structural Similarity Index (SSIM) between two batches of images.

    Args:
        patch_size (int or tuple, optional): If specified, split images into patches for local SSIM.
        eps (float): Small constant to avoid division by zero.
        k1 (float): Stability constant for luminance.
        k2 (float): Stability constant for contrast/structure.
        sigma (float): Standard deviation for Gaussian kernel in SSIM calculation.
    """

    def __init__(self, patch_size=None, eps=1e-8, k1=0.01, k2=0.03, sigma=1.5):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.k1 = k1
        self.k2 = k2

        # Pre-compute Gaussian kernel for SSIM
        self.sigma = sigma
        self.register_buffer('gaussian_kernel', self._create_gaussian_kernel(sigma).cuda())

    def _create_gaussian_kernel(self, sigma):
        """Create 2D Gaussian kernel for SSIM window."""
        kernel_size = int(4 * sigma + 1)
        x = torch.arange(kernel_size).float() - kernel_size // 2
        gauss = torch.exp(-x.pow(2) / (2 * sigma ** 2))
        gauss /= gauss.sum()
        return gauss.outer(gauss).unsqueeze(0).unsqueeze(0)  # Shape: [1, 1, kernel_size, kernel_size]

    def forward(self, x1, x2):
        """Compute SSIM between two image batches.

        Args:
            x1 (torch.Tensor): First image batch, shape [B, C, H, W].
            x2 (torch.Tensor): Second image batch, shape [B, C, H, W].

        Returns:
            torch.Tensor: SSIM scores per image in batch, shape [B].
        """
        if self.patch_size is not None:
            x1 = self.to_patches(x1, self.patch_size)
            x2 = self.to_patches(x2, self.patch_size)
        assert x1.shape == x2.shape, "Input images must be the same size"

        # Compute SSIM components
        mu1 = F.conv2d(x1, self.gaussian_kernel, padding='same')
        mu2 = F.conv2d(x2, self.gaussian_kernel, padding='same')

        mu1_sq = mu1.pow(2)
        mu2_sq = mu2.pow(2)
        mu1_mu2 = mu1 * mu2

        sigma1_sq = F.conv2d(x1 * x1, self.gaussian_kernel, padding='same') - mu1_sq
        sigma2_sq = F.conv2d(x2 * x2, self.gaussian_kernel, padding='same') - mu2_sq
        sigma12 = F.conv2d(x1 * x2, self.gaussian_kernel, padding='same') - mu1_mu2

        # Dynamic range (use max possible value if input is normalized)
        L = torch.max(torch.max(x1), torch.max(x2)) - torch.min(torch.min(x1), torch.min(x2))
        c1 = (self.k1 * L) ** 2
        c2 = (self.k2 * L) ** 2

        # SSIM formula
        ssim_map = ((2 * mu1_mu2 + c1) * (2 * sigma12 + c2)) / \
                   ((mu1_sq + mu2_sq + c1) * (sigma1_sq + sigma2_sq + c2) + self.eps)

        # Average over spatial dimensions and channels
        return ssim_map.mean(dim=[1, 2, 3])

    def to_patches(self, x, patch_size):
        """Split images into patches if patch_size is specified."""
        if isinstance(patch_size, int):
            patch_size = (patch_size, patch_size)

        b, c, h, w = x.shape
        x = x.unfold(2, patch_size[0], patch_size[0]).unfold(3, patch_size[1], patch_size[1])
        x = x.contiguous().view(b, c, -1, patch_size[0], patch_size[1])
        x = x.permute(0, 2, 1, 3, 4).reshape(-1, c, patch_size[0], patch_size[1])
        return x



# %% ../notebooks/api/05_metrics.ipynb 8
class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""

    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size) for patch_size in patch_sizes
        ]
        self.patch_weights = patch_weights

    def forward(self, x1, x2):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2))
        return torch.stack(scores, dim=0).sum(dim=0)

# %% ../notebooks/api/05_metrics.ipynb 9
from torchvision.transforms.functional import gaussian_blur


class Sobel(torch.nn.Module):
    def __init__(self, sigma):
        super().__init__()
        self.sigma = sigma
        self.filter = torch.nn.Conv2d(
            in_channels=1,
            out_channels=2,  # X- and Y-gradients
            kernel_size=3,
            stride=1,
            padding=1,  # Return images of the same size as inputs
            bias=False,
        )

        Gx = torch.tensor([[1, 0, -1], [2, 0, -2], [1, 0, -1]]).to(torch.float32).cuda()
        Gy = torch.tensor([[1, 2, 1], [0, 0, 0], [-1, -2, -1]]).to(torch.float32).cuda()
        G = torch.stack([Gx, Gy]).unsqueeze(1)
        self.filter.weight = torch.nn.Parameter(G, requires_grad=False)

    def forward(self, img):
        x = gaussian_blur(img, 5, self.sigma)
        x = self.filter(img)
        return x

# %% ../notebooks/api/05_metrics.ipynb 10
class GradientNormalizedCrossCorrelation2d(NormalizedCrossCorrelation2d):
    """Compute Normalized Cross Correlation between the image gradients of two batches of images."""

    def __init__(self, patch_size=None, sigma=1.0, **kwargs):
        super().__init__(patch_size, **kwargs)
        self.sobel = Sobel(sigma)

    def forward(self, x1, x2):
        return super().forward(self.sobel(x1), self.sobel(x2))

# %% ../notebooks/api/05_metrics.ipynb 11
from kornia.enhance.histogram import marginal_pdf, joint_pdf


class MutualInformation(torch.nn.Module):
    """Mutual Information."""

    def __init__(self, sigma=0.1, num_bins=256, epsilon=1e-10, normalize=True):
        super().__init__()
        self.register_buffer("sigma", torch.tensor(sigma).cuda())
        self.register_buffer("bins", torch.linspace(0.0, 1.0, num_bins).cuda())
        self.epsilon = epsilon
        self.normalize = normalize

    def forward(self, x1, x2):
        assert x1.shape == x2.shape
        B, C, H, W = x1.shape

        x1 = x1.view(B, H * W, C)
        x2 = x2.view(B, H * W, C)

        pdf_x1, kernel_values1 = marginal_pdf(x1, self.bins, self.sigma, self.epsilon)
        pdf_x2, kernel_values2 = marginal_pdf(x2, self.bins, self.sigma, self.epsilon)
        pdf_x1x2 = joint_pdf(kernel_values1, kernel_values2)

        H_x1 = -(pdf_x1 * (pdf_x1 + self.epsilon).log2()).sum(dim=1)
        H_x2 = -(pdf_x2 * (pdf_x2 + self.epsilon).log2()).sum(dim=1)
        H_x1x2 = -(pdf_x1x2 * (pdf_x1x2 + self.epsilon).log2()).sum(dim=(1, 2))

        mutual_information = H_x1 + H_x2 - H_x1x2
        if self.normalize:
            mutual_information = 2 * mutual_information / (H_x1 + H_x2)

        return mutual_information

# %% ../notebooks/api/05_metrics.ipynb 15
from projector.pose import RigidTransform, convert


class LogGeodesicSE3(torch.nn.Module):
    """
    Calculate the distance between transforms in the log-space of SE(3).
    This class inherits from torch.nn.Module, which is the base class for all neural network modules in PyTorch.
    The purpose of this class is to compute the geodesic distance between two SE(3) transformations.
    SE(3) is the special Euclidean group in 3D, which consists of rotations and translations.
    The log-space of SE(3) refers to the logarithmic map of the group, which converts group elements into a vector space.
    """

    def __init__(self):
        """
        Initialize the LogGeodesicSE3 module.
        This constructor calls the initializer of the parent class (torch.nn.Module) using super().
        """
        super().__init__()

    # def forward(
    #     self,
    #     pose_1: RigidTransform,
    #     pose_2: RigidTransform,
    # ) -> Float[torch.Tensor, "b"]:
    #     """
    #     Compute the geodesic distance between two SE(3) transformations.
    #
    #     Parameters:
    #     - pose_1: First SE(3) transformation (RigidTransform).
    #     - pose_2: Second SE(3) transformation (RigidTransform).
    #
    #     Returns:
    #     - A tensor of geodesic distances for each pair of transformations in the batch.
    #       The tensor has shape (b,), where b is the batch size.
    #
    #     The method computes the inverse of pose_1, composes it with pose_2, and then calculates the SE(3) log map.
    #     The norm of the log map is taken along the last dimension to get the geodesic distance.
    #     """
    #     return pose_2.compose(pose_1.inverse()).get_se3_log().norm(dim=1)

# %% ../notebooks/api/05_metrics.ipynb 18
from projector.pose import so3_log_map


class DoubleGeodesicSE3(torch.nn.Module):
    """
    Calculate the angular and translational geodesics between two SE(3) transformation matrices.
    """

    def __init__(
        self,
        sdd: float,  # Source-to-detector distance
        eps: float = 1e-6,  # Avoid overflows in sqrt
    ):
        super().__init__()
        self.sdr = sdd / 2
        self.eps = eps

        self.rot_geo = lambda r1, r2: self.sdr * so3_log_map(
            r1.transpose(-1, -2) @ r2
        ).norm(dim=-1)
        self.xyz_geo = lambda t1, t2: (t1 - t2).norm(dim=-1)

    def forward(self, pose_1: RigidTransform, pose_2: RigidTransform):
        r1, t1 = pose_1.convert("matrix")
        r2, t2 = pose_2.convert("matrix")
        rot = self.rot_geo(r1, r2)
        xyz = self.xyz_geo(t1, t2)
        dou = (rot.square() + xyz.square() + self.eps).sqrt()
        return rot, xyz, dou
